// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpfteiyxodigjvzzrwbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZnRlaXl4b2RpZ2p2enpyd2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTgzNzcsImV4cCI6MjA2MTczNDM3N30.mb-3EZOUxmMQuH8lc6hTQiynEc4jqgDnf3-AbEkz58s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);